config/routes.rb
Cscindy::Application.routes.draw do
  root 'pages#home'
  post 'pages/search', as: 'search'

  resources :tickets do
    resources :labors
  end
  get 'archive' => 'tickets#archive'
  
  resources :users

  resources :computers

  

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base  
  belongs_to :computer
  belongs_to :customer,   :class_name => "User"
  belongs_to :technician, :class_name => "User"

  composed_of :subtotal,
              :class_name => 'Money',
              :mapping => %w(price cents),
              :converter => Proc.new { |value| value.respond_to?(:to_money) ? value.to_money : Money.empty }
  
  composed_of :total,
              :class_name => 'Money',
              :mapping => %w(price cents),
              :converter => Proc.new { |value| value.respond_to?(:to_money) ? value.to_money : Money.empty }
  
  composed_of :tax,
              :class_name => 'Money',
              :mapping => %w(price cents),
              :converter => Proc.new { |value| value.respond_to?(:to_money) ? value.to_money : Money.empty }
  
  has_many :labors,   :dependent => :destroy
  has_many :parts,    :dependent => :destroy
  has_many :payments, :dependent => :destroy

  validates :customer_id, :presence => true
  validates :computer_id, :presence => true
  validates :issue,       :presence => true, :length => { :within => 10..255 }
  
  STATUSES = ['In Queue', 'Diagnosing', 'Fixing', 'Waiting', 'Completed', 'Closed']
  
  LOCAL_SALES_TAX = 0.07
  
  scope :in_queue,    where("status = ?", "In Queue")
  scope :in_limbo,    where("status = ?", "Waiting")
  scope :in_progress, where("status = ? OR status = ?", "Diagnosing", "Fixing")
  scope :recent,   -> { where("updated_at > ?", 6.months.ago) }
  scope :archived, -> { where("updated_at <= ?", 6.months.ago) }
end

# == Schema Information
#
# Table name: tickets
#
#  id            :integer(4)      not null, primary key
#  customer_id   :integer(4)
#  computer_id   :integer(4)
#  technician_id :integer(4)
#  created_at    :datetime
#  updated_at    :datetime
#  issue         :string(255)
#  status        :string(255)
#  subtotal      :integer(4)      default(0), not null
#  total         :integer(4)      default(0), not null
#  tax           :integer(4)      default(0), not null
#

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets_in_progress = Ticket.in_progress.recent.order("updated_at DESC")
    @tickets_in_queue = Ticket.in_queue.recent.order("updated_at DESC")
    @tickets_in_limbo = Ticket.in_limbo.recent.order("updated_at DESC")
  end

  def show
    @ticket = Ticket.find params[:id]
  end

  def archive
    @tickets_in_archive = Ticket.archived.order("updated_at DESC").paginate(page: params[:page], per_page: 30)
  end

  def update
    @ticket = Ticket.find params[:id]
    if @ticket
      if @ticket.update_attributes!(ticket_params)
        redirect_to @ticket
      else
        raise 'herp'.inspect
      end
    else
      raise 'derp'.inspect
    end
  end

  private
    def ticket_params
      params.require(:ticket).permit(:notes)
    end
  # end private
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_computer.html.haml
%section.computer.clickable{ data: { id: computer.id, url: computer_path(computer) } }
  %i.icon-laptop
  %b Computer:
  = computer.make
  = computer.model
  - if computer.charger
    w/charger

app/views/tickets/_customer.html.haml
%section.customer.clickable{ data: { id: customer.id, url: user_path(customer) } }
  %i.icon-user
  %b Customer:
  = customer.fname
  = customer.lname
  - if customer.tel.present?
    = number_to_phone customer.tel, delimiter: '.'
  - if customer.tel.present? && customer.tel2.present?
    = '|'
  - if customer.tel2.present?
    = number_to_phone customer.tel2, delimiter: '.'

app/views/tickets/_tickets_table.html.haml
%table.index
  %tr
    %th Customer
    %th Computer
    %th Issue
    %th.ticket_status Status
  - tickets.each do |ticket|
    %tr.clickable{ data: { id: ticket.id, url: ticket_path(ticket.id) } }
      %td.customer_name
        = ticket.customer.fname
        = ticket.customer.lname
      %td.computer_model
        = ticket.computer.make
        = ticket.computer.model
      %td= ticket.issue
      %td.ticket_status
        = ticket.status
        = time_ago_in_words ticket.updated_at
        ago

app/views/tickets/archive.html.haml
%h1.table_label In Archive
= render partial: 'tickets_table', locals: { tickets: @tickets_in_archive }
= will_paginate @tickets_in_archive, inner_window: 2

app/views/tickets/index.html.haml
%h1.table_label In Queue
= render partial: 'tickets_table', locals: { tickets: @tickets_in_queue }
%h1.table_label In Progress
= render partial: 'tickets_table', locals: { tickets: @tickets_in_progress }
%h1.table_label In Limbo
= render partial: 'tickets_table', locals: { tickets: @tickets_in_limbo }
%h1.table_label
  = link_to 'In Archive', archive_path

app/views/tickets/show.html.haml
= form_for @ticket, html: { class: 'submitless' } do |f|
  .ticket_show
    .column_left
      = render partial: 'customer', locals: { customer: @ticket.customer }
      = render partial: 'computer', locals: { computer: @ticket.computer }
      %section.issue
        %i.icon-comments
        %b Complaint:
        = @ticket.issue
      %section.notes
        .notes_label
          %i.icon-edit
          %b Notes:
        = f.text_area :notes, class: 'edit_notes'
    .column_right
      - if @ticket.technician.present?
        %section.technician
          %i.icon-user-md
          %b Technician:
          = @ticket.technician.fname
          = @ticket.technician.lname
      %section.status
        %i.icon-info-sign
        %b Status:
        = @ticket.status
        = time_ago_in_words @ticket.updated_at
        ago
        = f.select :status, Ticket::STATUSES, { include_blank: true }, class: 'status_select'
      %section.labor.clickable{ data: { url: ticket_labors_path(@ticket) } }
        %i.icon-wrench
        %b Labor:
        - if @ticket.labors.any?
          - if @ticket.labors.count > 1
            = @ticket.labors.count
            %br
          - @ticket.labors.each do |labor|
            = labor.service
            = labor.notes
            = humanized_money_with_symbol labor.price
            %br
        - else
          Diagnose & Call
      %section.parts
        %i.icon-keyboard
        %b Parts:
        - if @ticket.parts.any?
          - if @ticket.parts.count > 1
            = @ticket.parts.count
            %br
          - @ticket.parts.each do |part|
            = part.qty
            = part.item
            = humanized_money_with_symbol part.price
            = "Warranty: #{part.warranty}"
            %br
        - else
          None
      %section.balance
        %i.icon-money
        %b Balance:
        = humanized_money_with_symbol @ticket.total
        - if @ticket.subtotal > 0
          %br
          Subtotal:
          = humanized_money_with_symbol @ticket.subtotal
          Tax:
          = humanized_money_with_symbol @ticket.tax
      %section.payments
        %i.icon-credit-card
        %b Payments:
        - if @ticket.payments.any?
          - if @ticket.payments.count > 1
            = @ticket.payments.count
            %br
          - @ticket.payments.each do |payment|
            = humanized_money_with_symbol payment.price
            = payment.method
            = time_ago_in_words payment.updated_at
            ago
            %br
        - else
          None