config/routes.rb
Cscindy::Application.routes.draw do
  root 'pages#home'
  post 'pages/search', as: 'search'

  resources :tickets do
    resources :labors
  end
  get 'archive' => 'tickets#archive'
  
  resources :users

  resources :computers

  

end

app/models/labor.rb
class Labor < ActiveRecord::Base    
  belongs_to :ticket

  composed_of :price,
              :class_name => 'Money',
              :mapping => %w(price cents),
              :converter => Proc.new { |value| value.respond_to?(:to_money) ? value.to_money : Money.empty }
  
  validates :ticket_id, :presence => true
  validates :service,   :presence => true
  validates :price,     :presence => true
  
  SERVICES = ['Console Repair',
              'Data Recovery',
              'Diagnosis',
              'Laptop Disassembly',
              'Minimum Labor',
              'Premium Service',
              'Tune-up',
              'Virus Removal',
              'Wipe & Reload']
end

# == Schema Information
#
# Table name: labors
#
#  id         :integer(4)      not null, primary key
#  service    :string(255)
#  price      :integer(4)      default(0), not null
#  notes      :string(255)
#  ticket_id  :integer(4)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/labors_controller.rb
class LaborsController < ApplicationController
  def index
    @ticket = Ticket.find params[:ticket_id]
    if @ticket.present?
      @labors = @ticket.labors
    else
      raise 'ticket not found'.inspect
    end
  end

  def update
    @labor = Labor.find params[:id]
    if @labor.present?
      if @labor.update_attributes(labor_attributes)
        redirect_to ticket_labors_path(@labor.ticket)
      else
        raise 'unable to update labor'.inspect
      end
    else
      raise 'unable to find labor'.inspect
    end
  end

  def new
    @ticket = Ticket.find params[:ticket_id]
    @labor = @ticket.labors.new
  end

  def create
    if @ticket = Ticket.find(params[:ticket_id])
      if @ticket.labors.create!(labor_attributes)
        redirect_to ticket_labors_path(@ticket)
      else
        render :new
      end
    else
      raise 'unable to find ticket'.inspect
    end
  end
  
  private
    def labor_attributes
      params.require(:labor).permit(:service, :notes, :price)
    end
  #end private
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/views/labors/index.html.haml
%h1.table_label
  Labor Performed
.table.ticket_labors
  .thead
    .tr
      .td.service_label
        %i.icon-wrench
        %b Service
      .td.labor_notes_label
        %i.icon-edit
        %b Notes
      .td.cost_label
        %i.icon-money
        %b Cost
  .tbody
    - if @labors.any?
      - @labors.each do |labor|
        = form_for [@ticket, labor], html: { class: 'tr submitless' } do |f|
          .td.service= f.select :service, Labor::SERVICES, { include_blank: true }, class: 'service_select'
          .td.notes= f.text_field :notes
          .td= f.text_field :price, value: humanized_money_with_symbol(labor.price)
          = f.submit :submit, class: 'hidden'
    - else
      .tr
        .td.diagnose Diagnose & Call
        .td.diagnose
        .td.diagnose Free
%br
%nav.actions
  = link_to ticket_path(@ticket), class: 'button button-flat button-pill' do
    %i.icon-arrow-left
    Back To Ticket
  = link_to new_ticket_labor_path(@ticket), class: 'button button-flat button-pill' do
    %i.icon-plus
    Add Labor Charge

app/views/labors/new.html.haml
.derp
  %h1.table_label New Labor
  = form_for [@ticket, @labor] do |f|
    %table.new_ticket_labor
      %tr
        %th Service:
        %td= f.select :service, Labor::SERVICES, { include_blank: true }, class: 'service_select'
      %tr
        %th Notes:
        %td= f.text_field :notes
      %tr
        %th Price:
        %td= f.text_field :price, value: humanized_money_with_symbol(@labor.price)
    = f.submit 'Submit'